# Generated by Django 5.2 on 2026-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_contact_alter_music_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.CharField(blank=True, null=True, verbose_name='Category'),
        ),
    ]
