# Generated by Django 5.2 on 2026-03-18 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_category_remove_music_image_music_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.category'),
        ),
    ]
