# Generated by Django 5.2 on 2026-03-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='year_started',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(upload_to='Music'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(upload_to='Singer'),
        ),
    ]
