# Generated by Django 5.2 on 2026-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='popularity',
            field=models.BooleanField(default=False),
        ),
    ]
