# Generated by Django 5.2 on 2026-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
