# Generated by Django 5.2 on 2026-04-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_music_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='slug',
        ),
    ]
