# Generated by Django 5.2 on 2026-04-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_music_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
