# Generated by Django 5.2 on 2026-04-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_music_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer'),
        ),
    ]
