# Generated by Django 5.2 on 2026-05-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_alter_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.category'),
        ),
    ]
