# Generated by Django 5.2 on 2026-06-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_singer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='Category/کلاسیک.jpg', null=True, upload_to='Category/'),
        ),
    ]
