# Generated by Django 5.2 on 2026-06-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoyr', to='music.category'),
        ),
    ]
