# Generated by Django 5.2 on 2026-06-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_music_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_music', to='music.category'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_music', to='music.singer'),
        ),
    ]
